### PR TITLE
pull https://github.com/openshift/library-go/pull/1821

### PR DESCRIPTION
**Pull request by p0lyn0mial**

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/payload-job periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.18-periodics-e2e-aws

**Comment by smg247** [comment]
/payload-job periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.18-periodics-e2e-aws

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.18-periodics-e2e-aws

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.18-periodics-e2e-aws

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-csi

Trying a different job to see if the previous one is the problem.

**Comment by wangke19** [comment]
/pj-rehearse  periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.18-periodics-e2e-aws

**Comment by p0lyn0mial** [comment]
/close

in favour of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1750

**Pull request closed without merging**
