### PR TITLE
[release-4.15]OCPBUGS-35832: add SNO control plane high cpu usage alert

### PR DESCRIPTION
**Pull request by qJkee**
Manual backport of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1680 and https://github.com/openshift/cluster-kube-apiserver-operator/pull/1676

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
any conflicts when moving ?

**Comment by wangke19** [comment]
/hold
will do a pre-merge testing

**Comment by wangke19** [comment]
Pre-merge verified, detail see https://issues.redhat.com/browse/OCPBUGS-35832?focusedId=25063776&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25063776

**Pull request merged**
