### PR TITLE
OCPBUGS-19024: remove featuregate upgradeable controller that moved to cluster-config-operator

### PR DESCRIPTION
**Pull request by deads2k**
This controller moved to https://github.com/openshift/cluster-config-operator/tree/master/pkg/operator/featureupgradablecontroller in 4.14

/cherry-pick release-4.14

### CODE REVIEW

**Comment by wking** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.15-e2e-aws-sdn-techpreview

**Review by dgrisonnet — APPROVED** [review]
/lgtm
/approve

**Comment by dgrisonnet** [comment]
A relevant test is actually failing: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-apiserver-operator/1547/pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-gcp-operator/1702392736658755584

@deads2k can you have a look?

/unlgtm

**Comment by deads2k** [comment]
yes, thank you.

**Review by dgrisonnet — APPROVED** [review]
/lgtm

**Pull request merged**
