### PR TITLE
bug 1797657: increase the max-requests limits

### PR DESCRIPTION
**Pull request by deads2k**
more in line with real values.

/assign @smarterclayton

### CODE REVIEW

**Comment by sttts** [comment]
@deads2k What are real values? Why these?

**Comment by smarterclayton** [comment]
The limits were chosen during 3.x pre etcd2 where we had demonstrated hard boundaries on CPU use.  Based on all data I have in etcd3 period, a 3x increase is not an issue and any bug we hit where load is not effectively transferred would be a bug in the platform, not due to this.

/approve

**Comment by smarterclayton** [comment]
Basically 1k was chosen arbitrarily based on a CPU usage number in the early 3.x time period.  We have reclaimed somewhere between 5x and 10x CPU with etcd3, protobuf, improvements to internal efficiency, so a 3x bump gives us headroom without significantly increasing the risk of a failure due to excessive queries (we are likely to better respond with backpressure at multiple levels)

**Comment by sttts** [comment]
/lgtm

This will help for reasonably sized cluster. It might still not be enough for very dense clusters.

**Pull request merged**
