### PR TITLE
update manifest filenames to conform to expected CVO update payload format

### PR DESCRIPTION
**Pull request by juanvallejo**
update manifest filenames to conform to expected CVO update payload format

cc @smarterclayton @soltysh @rajatchopra

### CODE REVIEW

**Comment by smarterclayton** [comment]
Separate your component name parts with dashes as described before.  `_cluster-kube-apiserver-operator_`

**Comment by mfojtik** [comment]
@smarterclayton @juanvallejo we also need to update the Dockerfile to have the required label, correct?

**Pull request merged**
