### PR TITLE
bump library-go to get controller factory

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by sttts** [comment]
Duplicate of https://github.com/openshift/cluster-kube-apiserver-operator/pull/738.

**Comment by mfojtik** [comment]
@sttts not a duplicate, this follow up on controller factory

**Comment by mfojtik** [comment]
@sttts if @marun PR merge first, I can rebase

**Comment by mfojtik** [comment]
the e2e-aws failed because of SDN went down when OAS went up which means the OAS can't reach etcd... how nothing to do with changes in library-go.

**Pull request merged**
