### PR TITLE
Bug 1823933: Make default SCCs create-only by CVO

### PR DESCRIPTION
**Pull request by tkashem**

### CODE REVIEW

**Comment by tkashem** [comment]
(note to self)
This BZ will be used for the cherry-pick to 4.4 https://bugzilla.redhat.com/show_bug.cgi?id=1823934.

**Comment by sttts** [comment]
`level=error msg="Error: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='api.ci-op-28d5rqfx-63f8c.origin-ci-int-aws.dev.rhcloud.com.', type='A'] but it already exists]"`

/retest

**Pull request merged**
