### PR TITLE
Adjusting graph titles for API performance dashboard

### PR DESCRIPTION
**Pull request by bergerhoffer**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@tkashem Here are the minor adjustments to the titles on the API performance dashboard. I checked the other dashboards, which use title case, so that's what I did here (with some other minor adjustments).

One other thing that I'd recommend changing (but didn't know where it was located), is the "Apiserver" label at the top for the dropdown. I'd make that "API Server".

**Comment by tkashem** [comment]
@bergerhoffer I took your commit and added it to my changes.
https://github.com/openshift/cluster-kube-apiserver-operator/pull/1024

**Comment by tkashem** [comment]
> One other thing that I'd recommend changing (but didn't know where it was located), is the "Apiserver" label at the top for the dropdown. I'd make that "API Server".

This is a label and will require a change at relabeling rule at scrap time.

**Comment by bergerhoffer** [comment]
Closing, as the updates were included in #1024

**Pull request closed without merging**
