### PR TITLE
STOR-1051: Allow CSI inline volumes in all SCCs

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-1051
/hold until CSIInlineVolumeAdmission is GA
/cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
The [e2e tests](https://github.com/openshift/origin/pull/27682) merged and the [sippy results](https://sippy.dptools.openshift.org/sippy-ng/tests/4.13/details?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Afalse%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522serial%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522techpreview%2522%257D%252C%257B%2522columnField%2522%253A%2522name%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522CSIInlineVolumeAdmission%2522%257D%255D%252C%2522linkOperator%2522%253A%2522and%2522%257D&sort=asc&sortField=current_working_percentage) look good so far. I'll be on the lookout for test failures.
The `CSIInlineVolumeAdmission` feature gate was already dropped with the k8s 1.26 rebase, so I would be comfortable merging this now. It's basically the same as the SCC change for [generic ephemeral volumes](https://github.com/openshift/cluster-kube-apiserver-operator/pull/1380).
/unhold
/assign @jsafrane @deads2k

**Comment by dobsonj** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-techpreview-serial
to run the new e2e test against this PR with updated SCC's

**Comment by jsafrane** [comment]
/lgtm
from storage point of view
/assign @stlaz 
for auth team approval

**Comment by jsafrane** [comment]
@stlaz: we have an admission plugin that checks if a CSI driver is allowed in a privileged / baseline / restricted namespace: https://github.com/openshift/kubernetes/pull/1384, which does the real authorization work. Therefore it's OK to allow `csi` in all SCCs.

Enhancement: https://github.com/openshift/enhancements/blob/master/enhancements/storage/csi-inline-vol-security.md

**Comment by jsafrane** [comment]
I think it's an orthogonal admission plugin. It re-uses the same namespace annotations as Pod Security admission, but it has its own admission plugin and IMO we can declare it GA before PSa.

**Comment by dobsonj** [comment]
Jan is right, CSI enforcement comes from our admission plugin in https://github.com/openshift/kubernetes/pull/1384, not from PSA.

**Comment by stlaz** [comment]
I see, I slightly misunderstood these tables https://github.com/openshift/enhancements/blob/master/enhancements/storage/csi-inline-vol-security.md#workflow-description

**Comment by stlaz** [comment]
/lgtm
/assign @deads2k
for approval (I don't have approve privileges in this repo)

**Comment by deads2k** [comment]
my understanding is that currently the inline volume handling enforcement is techpreview, which means I expected this change to also be gated by techpreview.  Did the inline volume handling get promoted already?

**Comment by deads2k** [comment]
with https://github.com/openshift/api/pull/1402, this is safe.

/lgtm
/approve

**Pull request merged**
