### PR TITLE
OCPBUGS-13763: dont log jwt tokens

### PR DESCRIPTION
**Pull request by ibihim**
# What

Bump library-go to https://github.com/openshift/library-go/pull/1523.

# Why

It removes token from the logging.

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
Waiting for https://github.com/openshift/library-go/pull/1533

**Review by dgrisonnet — APPROVED** [review]
/lgtm
/approve

**Comment by dgrisonnet** [comment]
@ibihim the bug attached to this PR seems to be closed. Should we perhaps also close this PR?

**Comment by ibihim** [comment]
@dgrisonnet, I think the jira got closed and another got re-opened. I changed the target Jira.

**Pull request merged**
