### PR TITLE
Bug 1993800: bump(library-go): staticpod/installer: fix backoff of installers

### PR DESCRIPTION
**Pull request by sttts**
Bumping to get https://github.com/openshift/library-go/pull/1180

### CODE REVIEW

**Comment by wangke19** [comment]
Launched one 4.8 cluster with this PR successfully, verification steps see https://bugzilla.redhat.com/show_bug.cgi?id=1993800#c1

**Comment by sttts** [comment]
manually assigning label from https://github.com/openshift/cluster-kube-apiserver-operator/pull/1214#issuecomment-910092243

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.00

adding cherry-pick approved

**Pull request merged**
