### PR TITLE
OCPBUGS-11361: Revert "Merge pull request #1474 from benluddy/oapi-bump"

### PR DESCRIPTION
**Pull request by benluddy**
This reverts commit afaa2d15b7ffa657597735e8dc6597a510941211, reversing changes made to 6da6e15c14d5a71366190a3ace6b2d9daafc6ccf.

### CODE REVIEW

**Review by dgrisonnet — APPROVED** [review]
/lgtm
/approve

**Comment by benluddy** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1643269856813912064#1:build-log.txt%3A64

**Comment by deads2k** [comment]
we have clean installs.  this is reverting the last commit. Merging to unstick tech preview jobs.

**Pull request merged**
