### PR TITLE
Bug 1986167: kube-apiserver initContainer setup is not requesting required resources: cpu, memory

### PR DESCRIPTION
**Pull request by sanchezl**
Added resource requests for CPU and memory.

### CODE REVIEW

**Comment by dhellmann** [comment]
/hold

This PR is failing CI repeatedly. Should those jobs be skipped or are the failures valid?

**Comment by dhellmann** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped for today*

* Score: *0.70*
* Reason: *the author needs to investigate CI failures*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by dhellmann** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped for today*

* Score: *0.00*
* Reason: *skipping because "do-not-merge/hold" label found*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by sanchezl** [comment]
@dhellmann , the failing jobs don't seem to exist anymore. I think we can ignore them. They were failing because those jobs were trying to cherry-pick this PR on `master` instead of `release-4.7`.

**Comment by dhellmann** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped for today*

* Score: *0.00*
* Reason: *skipping because "do-not-merge/hold" label found*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by dhellmann** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped for today*

* Score: *0.00*
* Reason: *skipping because "do-not-merge/hold" label found*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Pull request closed without merging**
