### PR TITLE
Bug 1990610: prevent panic in startup monitor enablement check

### PR DESCRIPTION
**Pull request by deads2k**
if no infra is found, its early in the cluster's lifespan, just return
false for whether to enable the startup monitor

Found in https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.9-e2e-gcp-upgrade/1423126561342623744

### CODE REVIEW

**Comment by stbenjam** [comment]
/retitle Bug 1990610: prevent panic in startup monitor enablement check

**Comment by deads2k** [comment]
fixed gofmt.

retagging

**Pull request merged**
