### PR TITLE
Revert "bootstrap: add --advertise-address=pod.status.hostIP"

### PR DESCRIPTION
**Pull request by osherdp**
This reverts commit b713e9f553379558d9db34837079f6b190bd7b1a.

### CODE REVIEW

**Comment by sttts** [comment]
Why?

**Comment by osherdp** [comment]
I'm testing the behavior before this PR
It seems to cause the problems we have on assisted, so I want to confirm that (it's not for pushing)
/hold

**Comment by osherdp** [comment]
Anyway, we probably figured out the problem now
Closing

**Pull request closed without merging**
