### PR TITLE
bump(*): library-go with logging changes

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
NOTE: I really need to figure out why we always bumping `google.golang.org/appengine` ... it seems to be used by library-go and client-go and I think we should pin it to kube 1.12 levels in there to prevents these?

**Comment by deads2k** [comment]
/lgtm




> NOTE: I really need to figure out why we always bumping `google.golang.org/appengine` ... it seems to be used by library-go and client-go and I think we should pin it to kube 1.12 levels in there to prevents these?

icky, but ok.  YOu tried clearing the cache?

**Comment by mfojtik** [comment]
@deads2k yeah, `glide cc` before every bump, yet still getting these...

**Pull request merged**
