### PR TITLE
[WIP] Revert dev cert rotation

### PR DESCRIPTION
**Pull request by tkashem**
This reverts commit 65fc794b8aaa36a881323b26618ab46b7ed7defd, reversing
changes made to ff87de97de70b6d373a10cccc084497e44ec9bf3.

### CODE REVIEW

**Comment by tkashem** [comment]
this should merge before we cut for the next release

/hold

**Comment by mffiedler** [comment]
@tkashem @soltysh Is this still a candidate for 4.12?   Looks somewhat abandoned and the bz is flagged as a 4.12 blocker+

**Comment by mfojtik** [comment]
@tkashem, how about we try https://github.com/openshift/cluster-kube-apiserver-operator/pull/1384 ? :-)

**Comment by tkashem** [comment]
> @tkashem, how about we try #1384 ? :-)

based on the conversation we had, does not look like its ready, so 4.12 we still have to go with this PR i think

**Comment by tkashem** [comment]
opened for 4.12 - https://github.com/openshift/cluster-kube-apiserver-operator/pull/1401

**Pull request closed without merging**
