### PR TITLE
encryption: switch to library-go implementation

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
the tests are failing on `bootstrap` phase, lots of errors like `Failed to dial etcd-1.ci-op-m4xx3qh9-cd5db.origin-ci-int-aws.dev.rhcloud.com:2379: grpc: the connection is closing; please retry`

**Comment by p0lyn0mial** [comment]
/hold

we need to investigate why the jobs are failing.

**Comment by sttts** [comment]
Terraform error

/retest

**Pull request merged**
