### PR TITLE
[release-4.16]OCPBUGS-35831: add SNO control plane high cpu usage alert

### PR DESCRIPTION
**Pull request by qJkee**
Manual backport of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1680 and https://github.com/openshift/cluster-kube-apiserver-operator/pull/1676

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
any conflicts when moving ?

**Comment by wangke19** [comment]
PR has been per-merge verified, got the expected results, detail see https://issues.redhat.com/browse/OCPBUGS-35831?focusedId=24982008&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24982008

**Comment by tkashem** [comment]
/hold

(let's hold until we clear 4.16 GA)

**Pull request merged**
