### PR TITLE
add feature flags observer

### PR DESCRIPTION
**Pull request by deads2k**
If we agree it should look roughly like this, I'll promote it to library-go and clone into our other repos.

@openshift/sig-master

### CODE REVIEW

**Comment by sjenning** [comment]
fyi @rphillips

**Comment by deads2k** [comment]
Neat, no feature gate instance

**Comment by rphillips** [comment]
nice. lgtm

**Comment by deads2k** [comment]
waiting on https://github.com/openshift/installer/pull/1546

**Comment by eparis** [comment]
https://github.com/openshift/api/pull/278

**Comment by deads2k** [comment]
rebased on @mfojtik's bump and fixed a few more accidentally pinned ones.

**Pull request merged**
