### PR TITLE
Bug 1739504: block upgrades on techpreviewnoupgrade featuregates

### PR DESCRIPTION
**Pull request by tnozicka**
Rebased https://github.com/openshift/cluster-kube-apiserver-operator/pull/540

/cc @mfojtik

### CODE REVIEW

**Comment by tnozicka** [comment]
@jwforres @derekwaynecarr can you pls approve the cherrypick?

**Comment by derekwaynecarr** [comment]
does this change make the meaning of tech preview no upgrade:

no upgrade even with a given minor version
no upgrade across minor versions

please confirm, and this will go out next week.

**Comment by eparis** [comment]
/hold
this belongs in CVO.
/lgtm cancel

**Comment by tnozicka** [comment]
/close
leaving it unhadled until installer comes with it's own fix. (although this is merged in 4.2)

**Pull request closed without merging**
