### PR TITLE
API-1509: Enable AESGCM encryption

### PR DESCRIPTION
**Pull request by dgrisonnet**

### CODE REVIEW

**Comment by mfojtik** [comment]
this is just bump

/lgtm
/approve

**Comment by dgrisonnet** [comment]
Restarting since must-gather failed.

/retest-required

**Comment by dgrisonnet** [comment]
Retrying since the `TestEncryptionTypeAESCBC` test is passing when I test locally.

**Comment by deads2k** [comment]
Staff-eng agrees that this is approved for backport to 4.13.  Decision criteria include
1. pretest passed by QE
2. PR was tagged prior to merge, but CI failed due to a *different* failing test that has since been fixed
3. this enables a security feature that is required to pass audits
4. this is an incremental change, not a significant rewrite.
5. Default enablement (which is likely to be approved too), is a separate step that is low risk, *after* this merges due to TechPreview-first

@dgrisonnet @tkashem let me know when the backport is up and I'll label it.

**Comment by dgrisonnet** [comment]
Closing in favor of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1449 that is also enabling AESGCM and on top of that adds e2e tests verifying that the feature works as expected.

**Pull request closed without merging**
