### PR TITLE
Bug 1869913: connectivity outage events duplicated when status updates are retried

### PR DESCRIPTION
**Pull request by sanchezl**
- check-endpoints: don't duplicate events on update error
- check-endpoints: force flush ignored

### CODE REVIEW

**Comment by deads2k** [comment]
I think we may need something different. Probably a separate ratelimiter or different correlators for these events.   I think the event recorder has options.

**Comment by sanchezl** [comment]
/test e2e-aws-upgrade
--

**Comment by deads2k** [comment]
/close

this doesn't practically happen and the existing de-duping logic applies.

**Pull request closed without merging**
