### PR TITLE
Disable local-storage features

### PR DESCRIPTION
**Pull request by gnufied**
Disable local-storage feature as per  JIRA- STOR-183

### CODE REVIEW

**Comment by gnufied** [comment]
As expected local-storage tests are failing but https://github.com/openshift/origin/pull/21881 should disable them.

**Comment by deads2k** [comment]
Given that the bootstrap control plane shouldn't put bad data in, you probably need to update https://github.com/openshift/cluster-kube-apiserver-operator/blob/master/bindata/bootkube/config/bootstrap-config-overrides.yaml too

**Comment by sttts** [comment]
@deads2k the defaultconfig is also the basis for the bootstrap control plane. So no need for an override.

**Pull request merged**
