### PR TITLE
Update API alerts after recent bump to k8s 1.25

### PR DESCRIPTION
**Pull request by soltysh**
/assign @sanchezl @mfojtik

### CODE REVIEW

**Comment by mfojtik** [comment]
/override ci/prow/e2e-aws-serial
/approve

Lets move this forward, the serial test failures are unrelated to the operator and we can fix them next.

**Comment by mfojtik** [comment]
/hold

for @soltysh approval

**Comment by soltysh** [comment]
The failures in this PR are not related with this particular change, they are failing on issues described in https://issues.redhat.com/browse/RCMAUTO-6093. Additionally this fixes API alerts which in the long run will ensure they are not firing unnecessarily. 
/override ci/prow/e2e-aws-ovn
/override ci/prow/e2e-upgrade

**Pull request merged**
