### PR TITLE
OCPBUGS-13547: Remove featureset flag and use only the manifest

### PR DESCRIPTION
**Pull request by deads2k**
The manifest now exists in every install and can be used by bootstrapping.  The installer passes the arg now, so we can update the operator to only honor the manifest and eliminate interpretation.

### CODE REVIEW

**Comment by deads2k** [comment]
last cleanup for command related to external CCM feature unrevert

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by deads2k** [comment]
cleaning up remnants for external cloud provider

/retest

**Pull request merged**
