### PR TITLE
disable apiextensions.k8s.io/v1beta1 and admissionregistration.k8s.io/v1beta1

### PR DESCRIPTION
**Pull request by atiratree**
to disable it even before we hit k8s 1.22

### CODE REVIEW

**Comment by atiratree** [comment]
fix for the origin tests: https://github.com/openshift/origin/pull/26269

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/hold
until we get that origin PR merged

**Comment by atiratree** [comment]
I think after this one we should be good to go https://github.com/openshift/origin/pull/26280/

**Comment by soltysh** [comment]
The upgrade failures seemed to be related with a problem that was fixed in this revert https://github.com/openshift/cluster-monitoring-operator/pull/1259

**Pull request merged**
