### PR TITLE
[WIP] Remove audit pkg to use library-go

### PR DESCRIPTION
**Pull request by EmilyM1**
This is the removal of pkg/operator/audit internal to the operator so that it can read the audit pkg from lib-go.

### CODE REVIEW

**Comment by stlaz** [comment]
how is this PR different from https://github.com/openshift/cluster-kube-apiserver-operator/pull/1074?

**Comment by tkashem** [comment]
@EmilyM1 looks like you need to update dependency, `make update-vendor` i think.

**Pull request closed without merging**
