### PR TITLE
[release-4.14] OCPBUGS-31354: Create separate SNO alert for control plane high cpu usage

### PR DESCRIPTION
**Pull request by qJkee**
Create separate SNO alert for control plane high cpu usage. This alert is also aware of workload partitioning and adjusts threshold if workload partitioning is enabled.

(cherry picked from commit d92b46166259ef43918e9f7cd6bc62f09a806d1f)

### CODE REVIEW

**Comment by wangke19** [comment]
I have completed pre-merge verification for this PR, got the expected results, detail see https://issues.redhat.com/browse/OCPBUGS-31354?focusedId=24636314&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24636314

**Review by sanchezl — APPROVED** [review]
/label backport-risk-assessed

**Comment by wangke19** [comment]
@sanchezl Please add label `backport-risk-assessed`

**Comment by p0lyn0mial** [comment]
shouldn't we backport to 4-15 first ?

**Pull request closed without merging**
