### PR TITLE
Bug 1948311: DelegatingAuthenticationOptions TokenReview request timeout 

### PR DESCRIPTION
**Pull request by p0lyn0mial**
proof for https://github.com/openshift/kubernetes-apiserver/pull/30

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/hold

for a real bump

**Comment by p0lyn0mial** [comment]
/hold

for a manual test

**Comment by deads2k** [comment]
/lgtm

release hold once you manually confirm the audit log.

**Comment by p0lyn0mial** [comment]
before: 
```
cat master-1.all.log master-2.all.log master-3.all.log | jq --slurp '.[] | select(.verb == "watch" and .objectRef.name == "extension-apiserver-authentication")' | jq -s '.[] | select(.user.username == "system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator")' | wc -l
    3084
 ```
 
 after:
 ```
 cat master-1.all.log master-2.all.log master-3.all.log | jq --slurp '.[] | select(.verb == "watch" and .objectRef.name == "extension-apiserver-authentication")' | jq -s '.[] | select(.user.username == "system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator")' | wc -l
    2110
```

it looks like after applying the fix, watches are terminated after the timeout specified in the query parameters, for example:

```
{
  "kind": "Event",
  "apiVersion": "audit.k8s.io/v1",
  "level": "Metadata",
  "auditID": "2626a946-4fdf-49cf-9fd7-a2fd9713763d",
  "stage": "ResponseComplete",
  "requestURI": "/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dextension-apiserver-authentication&resourceVersion=195977&timeout=6m38s&timeoutSeconds=398&watch=true",
  "verb": "watch",
  "user": {
    "username": "system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator",
    "uid": "490d3f70-8a87-4631-a5fb-644401bb7c13",
    "groups": [
      "system:serviceaccounts",
      "system:serviceaccounts:openshift-kube-apiserver-operator",
      "system:authenticated"
    ]
  },
  "sourceIPs": [
    "10.0.252.227"
  ],
  "userAgent": "cluster-kube-apiserver-operator/v0.0.0 (linux/amd64) kubernetes/$Format",
  "objectRef": {
    "resource": "configmaps",
    "namespace": "kube-system",
    "name": "extension-apiserver-authentication",
    "apiVersion": "v1"
  },
  "responseStatus": {
    "metadata": {},
    "status": "Success",
    "message": "Connection closed early",
    "code": 200
  },
  "requestReceivedTimestamp": "2021-04-19T15:55:18.003497Z",
  "stageTimestamp": "2021-04-19T16:01:56.004319Z",
  "annotations": {
    "authentication.k8s.io/legacy-token": "system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator",
    "authorization.k8s.io/decision": "allow",
    "authorization.k8s.io/reason": "RBAC: allowed by ClusterRoleBinding \"system:openshift:operator:kube-apiserver-operator\" of ClusterRole \"cluster-admin\" to ServiceAccount \"kube-apiserver-operator/openshift-kube-apiserver-operator\""
  }
}
```

**Comment by deads2k** [comment]
2110 watches for that configmap is still too high.  I'm open to merging this if you choose to, but when we find the next offender you'll need to fix that too.  Release the hold if and when you choose to.

**Comment by p0lyn0mial** [comment]
> 2110 watches for that configmap is still too high. I'm open to merging this if you choose to, but when we find the next offender you'll need to fix that too. Release the hold if and when you choose to.|

Yes, I think it is worth further investigation. I will have a look tomorrow morning.

**Comment by p0lyn0mial** [comment]
OK, it looks like my previous query was broken.

before (by user):
```
cat master-1.all.log master-2.all.log master-3.all.log | jq --slurp '.[] | select(.verb == "watch" and .objectRef.name == "extension-apiserver-authentication")' | jq -s '.[] | select(.user.username == "system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator" and .stage == "ResponseComplete")' | jq -s 'group_by(.user.username) | .[] | {"count": length, "user":.[0].user.username}' | jq -s 'sort_by(.count)'
[
  {
    "count": 1248,
    "user": "system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator"
  }
]
```

after (by user):
```
cat master-1.all.log master-2.all.log master-3.all.log | jq --slurp '.[] | select(.verb == "watch" and .objectRef.name == "extension-apiserver-authentication")' | jq -s '.[] | select(.user.username == "system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator" and .stage == "ResponseComplete")' | jq -s 'group_by(.user.username) | .[] | {"count": length, "user":.[0].user.username}' | jq -s 'sort_by(.count)'
[
  {
    "count": 26,
    "user": "system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator"
  }
]
```


before (by status code):
```
cat master-1.all.log master-2.all.log master-3.all.log | jq --slurp '.[] | select(.verb == "watch" and .objectRef.name == "extension-apiserver-authentication")' | jq -s '.[] | select(.user.username == "system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator" and .stage == "ResponseComplete")' | jq -s 'group_by(.responseStatus.code) | .[] | {"count": length, "code":.[0].responseStatus.code}' | jq -s 'sort_by(.count)'
[
  {
    "count": 21,
    "code": 429
  },
  {
    "count": 1227,
    "code": 200
  }
]
```

after (by status code):
```
cat master-1.all.log master-2.all.log master-3.all.log | jq --slurp '.[] | select(.verb == "watch" and .objectRef.name == "extension-apiserver-authentication")' | jq -s '.[] | select(.user.username == "system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator" and .stage == "ResponseComplete")' | jq -s 'group_by(.responseStatus.code) | .[] | {"count": length, "code":.[0].responseStatus.code}' | jq -s 'sort_by(.count)'
[
  {
    "count": 11,
    "code": 429
  },
  {
    "count": 15,
    "code": 200
  }
]
```

**Pull request merged**
