### PR TITLE
NO MERGE: PR for testing `/payload`

### PR DESCRIPTION
**Pull request by petr-muller**
@deads2k told me I can use this repository to test `/payload` Prow plugin. Hence, opening this PR. Sorry for notifications.

### CODE REVIEW

**Comment by petr-muller** [comment]
https://payload-testing-ui-bbguimaraes.apps.ci.l2s4.p1.openshiftapps.com/runs/ci/686a2450-4256-11ec-9b44-50db765473cc-0

**Comment by hongkailiu** [comment]
@anezkamll 

The best acceptance test ever!

**Pull request closed without merging**
