### PR TITLE
[4.1] - Fix deps

### PR DESCRIPTION
**Pull request by tnozicka**
someone didn't commit a bump correctly, this fixes it (https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-apiserver-operator/534/pull-ci-openshift-cluster-kube-apiserver-operator-release-4.1-verify-deps/39)

/cc @sttts @deads2k

### CODE REVIEW

**Comment by tnozicka** [comment]
/assign @jwforres 
(for cherry-pick-approved label)

**Comment by jwforres** [comment]
Please still add a bugzilla indicating that you are fixing our vendored dependencies for this repo. As well as provide a more descriptive PR title. All of this ends up in our changelog. I'll assume there is no 4.2 BZ for this since it was specific to how we bumped deps in this 4.1 release stream.

Do we know how we were able to get the repo into this state when there are tests that are validating this?

**Comment by smarterclayton** [comment]
Picked into #531 so we can merge the damn thing

**Comment by tnozicka** [comment]
> Please still add a bugzilla indicating that you are fixing our vendored dependencies for this repo. 

yeah, @eparis didn't want an empty BZ (or this PR) so we don't have an image with no changes.

> Do we know how we were able to get the repo into this state when there are tests that are validating this?

The check is optional so if people ignore it or pre-lgtm it merges broken. (I am trying to find consensus on moving it to required and use `/override` if the repo is down and we need urgent merge.) 

@smarterclayton picked it into another backport PR
/close

**Pull request closed without merging**
