### PR TITLE
OCPBUGS-17436: Unrevert 1536 and 1538.

### PR DESCRIPTION
**Pull request by benluddy**
Change to test has merged: https://github.com/openshift/origin/pull/28214. It should not be sensitive to differences in the set of served APIs anymore.

### CODE REVIEW

**Comment by benluddy** [comment]
https://github.com/openshift/cluster-kube-apiserver-operator/pull/1541#issuecomment-1691643969

/hold

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by dinhxuanvu** [comment]
Both required tests failed on installer error it seems.
/retest-required

**Comment by benluddy** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview-serial

**Comment by benluddy** [comment]
> msg=Error: creating EC2 Instance: InsufficientInstanceCapacity

/test e2e-aws-ovn-serial

**Comment by benluddy** [comment]
> event [ns/openshift-marketplace pod/certified-operators-jd2br node/ci-op-kb2qxvxl-b7a42-xhc4b-master-2 hmsg/96ae460b2e - pathological/true interesting/true reason/BackOff Back-off restarting failed container registry-server in pod certified-operators-jd2br_openshift-marketplace(e65e5ee7-ff02-4682-87ae-48dcfa2c84c1)] happened 53 times}

There seems to have briefly been a broken certified-operators index image producing this failure across multiple test jobs.

/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview-serial

**Pull request merged**
