### PR TITLE
make PodSecurity admission enforce restricted globally

### PR DESCRIPTION
**Pull request by stlaz**
Also removes the warn and audit levels as these are driven
by the enforcement policy.

/assign @ibihim 
/assign @deads2k

### CODE REVIEW

**Comment by stlaz** [comment]
supersedes https://github.com/openshift/cluster-kube-apiserver-operator/pull/1339

**Comment by stlaz** [comment]
/hold
until we fix ovn

**Comment by dgoodwin** [comment]
/hold

Source PR may have taken out CI. Investigating.

**Comment by stlaz** [comment]
/test k8s-e2e-gcp
this should be an unrelated failure

**Comment by stlaz** [comment]
/test k8s-e2e-gcp
installation failed :disappointed:

**Comment by stlaz** [comment]
/retest
503 on registry service

**Comment by stlaz** [comment]
/retest
I assume somebody broke something upstream. e2e-aws-serial should be fixed now and the upgrade tests should not be broken.

**Comment by MaysaMacedo** [comment]
/retest-required

Testes are now [being skipped](https://github.com/openshift/kubernetes/pull/1339) for `k8s-e2e-gcp`

**Comment by stlaz** [comment]
/test e2e-aws-ovn
cluster install issue

**Review by ibihim — APPROVED** [review]
/lgtm

**Pull request merged**
