### PR TITLE
Update library-go to 80f9619c2

### PR DESCRIPTION
**Pull request by pacevedom**
Relates to https://github.com/openshift/library-go/pull/1347, where we increase missing static pods timeout in case we are in single node.

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
Could you split it into 2 commits? One for the bump and the second for the actual change. Thanks.

**Comment by pacevedom** [comment]
> Could you split it into 2 commits? One for the bump and the second for the actual change. Thanks.

Sure. Should I do the same for all 4 operators?

**Comment by p0lyn0mial** [comment]
/lgtm
/approve

Thanks!

**Comment by p0lyn0mial** [comment]
> Sure. Should I do the same for all 4 operators?

Yes, please

**Pull request merged**
