### PR TITLE
[release-4.13] OCPBUGS-19825: Update staticpod file permissions to conform with CIS benchmarks

### PR DESCRIPTION
**Pull request by ardaguclu**
This PR bumps library-go to fetch the changes come with;
* https://github.com/openshift/library-go/pull/1570
* https://github.com/openshift/library-go/pull/1536
* https://github.com/openshift/library-go/pull/1546

### CODE REVIEW

**Review by dgrisonnet — APPROVED** [review]
/lgtm
/approve

**Review by soltysh — APPROVED** [review]
/label backport-risk-assessed

**Comment by ardaguclu** [comment]
@gangwgr could you please add cherry-pick-approved label?. Thanks.

**Pull request merged**
