### PR TITLE
fix status

### PR DESCRIPTION
**Pull request by deads2k**

### CODE REVIEW

**Comment by mfojtik** [comment]
interesting, the logs for kube apiserver operator is empty, but I can see the events.

/retest

**Comment by smarterclayton** [comment]
Are we sure this fixes the issue?

**Comment by deads2k** [comment]
We are sure it fixes status instead of being stuck.

/retest

**Comment by abhinavdahiya** [comment]
@deads2k  running locally i'm seeing
```console
[root@adahiya-0-bootstrap ~]# oc --config /opt/openshift/auth/kubeconfig get clusteroperator
NAME                                        VERSION   AVAILABLE   PROGRESSING   FAILING   SINCE
openshift-cluster-kube-apiserver-operator                                       False

[root@adahiya-0-bootstrap ~]# oc --config /opt/openshift/auth/kubeconfig get clusteroperator -oyaml
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: ClusterOperator
  metadata:
    creationTimestamp: 2018-12-11T17:40:46Z
    generation: 1
    name: openshift-cluster-kube-apiserver-operator
    namespace: ""
    resourceVersion: "1676"
    selfLink: /apis/config.openshift.io/v1/clusteroperators/openshift-cluster-kube-apiserver-operator
    uid: e4591369-fd6b-11e8-9c92-e674e5383b45
  spec: {}
  status:
    conditions:
    - lastTransitionTime: 2018-12-11T17:42:20Z
      status: "False"
      type: Failing
    extension: null
    version: ""
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

```console
[root@adahiya-0-bootstrap ~]# oc --config /opt/openshift/auth/kubeconfig get kubeapiserveroperatorconfigs instance -oyaml
apiVersion: kubeapiserver.operator.openshift.io/v1alpha1
kind: KubeAPIServerOperatorConfig
metadata:
  creationTimestamp: 2018-12-11T17:40:46Z
  generation: 3
  name: instance
  resourceVersion: "1674"
  selfLink: /apis/kubeapiserver.operator.openshift.io/v1alpha1/kubeapiserveroperatorconfigs/instance
  uid: e44fdb24-fd6b-11e8-9c92-e674e5383b45
spec:
  forceRedeploymentReason: ""
  managementState: Managed
  observedConfig:
    admissionPluginConfig:
      openshift.io/RestrictedEndpointsAdmission:
        configuration:
          restrictedCIDRs:
          - 10.128.0.0/14
          - 172.30.0.0/16
    servicesSubnet: 172.30.0.0/16
    storageConfig:
      urls:
      - https://adahiya-0-etcd-0.tt.testing:2379
  operandSpecs: null
  unsupportedConfigOverrides:
    oauthConfig:
      masterCA: /etc/kubernetes/static-pod-resources/configmaps/client-ca/ca-bundle.crt
      masterPublicURL: https://adahiya-0-api.tt.testing:6443
      masterURL: https://adahiya-0-api.tt.testing:6443
status:
  conditions:
  - lastTransitionTime: 2018-12-11T17:40:46Z
    status: "False"
    type: InstallerControllerFailing
  - lastTransitionTime: null
    status: "False"
    type: ConfigObservationFailing
  - lastTransitionTime: null
    status: "False"
    type: RevisionControllerFailing
  - lastTransitionTime: 2018-12-11T17:40:48Z
    status: "False"
    type: BackingResourceControllerFailing
  - lastTransitionTime: 2018-12-11T17:40:57Z
    status: "False"
    type: TargetConfigReconcilerFailing
  generations: null
  latestAvailableRevision: 2
  nodeStatuses:
  - currentRevision: 2
    lastFailedRevision: 0
    lastFailedRevisionErrors: null
    nodeName: adahiya-0-master-0
    targetRevision: 0
  readyReplicas: 0
  version: ""
```

The status is still wrong

**Comment by abhinavdahiya** [comment]
Oops, forgot to hold this :P @deads2k

**Pull request merged**
