### PR TITLE
Revert "drop log-file flag removed in 1.26"

### PR DESCRIPTION
**Pull request by derekhiggins**
This reverts commit 6d1def163cf897b6ca54da16bdc1f444bbae5607.

This results in log files getting wiped on restart, I'm also investigating some CI failures and would like to rule
this out as a cause.

### CODE REVIEW

**Comment by derekhiggins** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm

**Comment by deads2k** [comment]
This fixes a log file regression.  Tagging.

/lgtm
/approve

**Comment by tkashem** [comment]
/hold

@sanchezl  has an alternative https://github.com/openshift/cluster-kube-apiserver-operator/pull/1427 
@sanchezl feel free to cancel the hold if you want to go with revert

**Comment by deads2k** [comment]
/hold cancel

the fix can come after.  We will get master working again first.

**Pull request merged**
