### PR TITLE
Switch openshift/kas-o to go1.11

### PR DESCRIPTION
**Pull request by soltysh**
/assign @tnozicka @sttts
Requires https://github.com/openshift/release/pull/3486

### CODE REVIEW

**Comment by soltysh** [comment]
/hold 
for requirement to merge first

**Comment by sttts** [comment]
/hold

Until openshift/release#3486 merges.

**Comment by soltysh** [comment]
Prereq merged.
/retest

**Comment by tnozicka** [comment]
/lgtm
/approve

/hold cancel
(prereq merged, and also given the different formatting, CI would enforce the order here anyways)

**Pull request merged**
