### PR TITLE
Vendor: update library-go for ibmcloud provider

### PR DESCRIPTION
**Pull request by jonesbr17**
Pull in support for ibmcloud added in https://github.com/openshift/library-go/pull/1161

### CODE REVIEW

**Comment by rtheis** [comment]
@JoelSpeed ptal

**Comment by JoelSpeed** [comment]
This will make KASO set KAS as `--cloud-provider=external` when deployed onto IBM. This is required for the IBM CCM integration.

/lgtm

**Comment by rtheis** [comment]
@jonesbr17 can you please resolve the merge conflicts?

**Comment by jonesbr17** [comment]
No longer needed, this was handled by https://github.com/openshift/cluster-kube-apiserver-operator/pull/1228

**Pull request closed without merging**
