### PR TITLE
Bug 1967090: webhookauth observer: set cache TTL to 30s

### PR DESCRIPTION
**Pull request by stlaz**
Set webhook authenticator's cache TTL to 30s to prevent very early
oauthaccesstoken timeouts.

---
as described in https://github.com/openshift/enhancements/pull/403

/assign @deads2k 
cc @s-urbaniak

### CODE REVIEW

**Comment by stlaz** [comment]
BZ tbd

**Review by slaskawi — APPROVED** [review]
LGTM but I think it would be good to add a test somewhere.

**Pull request merged**
