### PR TITLE
[release 4-1] Bug 1810186: Components using globs in Dockerfile COPY commands may break on OCP 4

### PR DESCRIPTION
**Pull request by p0lyn0mial**

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
BTW: The BZ says that we should only fix `Dockerfile.rhel7` file.

This repository also has [Dockerfile](https://github.com/openshift/cluster-kube-apiserver-operator/blob/release-4.1/Dockerfile), does it mean it's not used and could be removed?

**Comment by eparis** [comment]
The bug was closed wontfix? Should this just be closed?

**Comment by bparees** [comment]
> The bug was closed wontfix? Should this just be closed?

no. will ping you

**Comment by bparees** [comment]
@eparis i've manually overridden this w/ a valid bug label, i provided an explanation to you in slack.

**Comment by p0lyn0mial** [comment]
`ci/prow/e2e-aws`  seems to be broken for a very long time :(

https://prow.svc.ci.openshift.org/job-history/origin-ci-test/pr-logs/directory/pull-ci-openshift-cluster-kube-apiserver-operator-release-4.1-e2e-aws?buildId=

**Comment by p0lyn0mial** [comment]
`Run multi-stage test e2e-aws - e2e-aws-gather-audit-logs container test` is broken
```
sent 313 bytes  received 313,523 bytes  125,534.40 bytes/sec
total size is 312,076  speedup is 0.99
clusterrolebinding.rbac.authorization.k8s.io/must-gather-8xfxc deleted
namespace/openshift-must-gather-w9mm8 deleted
mv: cannot stat '/tmp/artifacts/tmp.wfvD8vKGgG/*/audit_logs': No such file or directory
```

**Comment by p0lyn0mial** [comment]
/hold

ci/prow/e2e-aws seems to be broken for a very long time :(

https://prow.svc.ci.openshift.org/job-history/origin-ci-test/pr-logs/directory/pull-ci-openshift-cluster-kube-apiserver-operator-release-4.1-e2e-aws?buildId=


`Run multi-stage test e2e-aws - e2e-aws-gather-audit-logs container test` is broken
```
sent 313 bytes  received 313,523 bytes  125,534.40 bytes/sec
total size is 312,076  speedup is 0.99
clusterrolebinding.rbac.authorization.k8s.io/must-gather-8xfxc deleted
namespace/openshift-must-gather-w9mm8 deleted
mv: cannot stat '/tmp/artifacts/tmp.wfvD8vKGgG/*/audit_logs': No such file or directory
```

**Pull request merged**
