### PR TITLE
WRKLDS-649: Guard pod set readiness probe endpoint explicitly

### PR DESCRIPTION
**Pull request by ingvagabund**
Pulling https://github.com/openshift/library-go/pull/1457 and setting the readiness endpoint to /readyz explicitly.

### CODE REVIEW

**Comment by ingvagabund** [comment]
/hold
until https://github.com/openshift/library-go/pull/1457 merges

**Review by dgrisonnet — COMMENTED** [review]
/lgtm
/approve

**Comment by deads2k** [comment]
yay!  I just found this.  Very glad to see this landing.

**Comment by ingvagabund** [comment]
e2e-gcp-operator blocked by https://github.com/openshift/cluster-kube-apiserver-operator/pull/1436

**Pull request merged**
