### PR TITLE
token inactivity e2e: wait for KAS to stop progressing

### PR DESCRIPTION
**Pull request by stlaz**
The token inactivity tests would only wait for KAS-o to
start progressing and then would attempt to check KAS
revisions to be stable, but these could have still been
the previous API server revisions.

-----

it's a hypothesis, let's see the number of successful runs

### CODE REVIEW

**Comment by deads2k** [comment]
show three clean `/test ci/prow/e2e-aws-operator` in a rows and you can remove the hold

/lgtm
/hold

**Comment by stlaz** [comment]
/retest
**1.**

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-apiserver-operator/1047/pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-aws-operator/1362030715335610368 -> the job is red, but TestTokenInactivityTimeout is green

**Comment by stlaz** [comment]
/test e2e-aws-operator
all the tests were green

**Comment by stlaz** [comment]
/test e2e-aws
**3.** all e2e-aws-operator tests were green

**Pull request merged**
