### PR TITLE
bump(k8s.io/*): 1.21

### PR DESCRIPTION
**Pull request by soltysh**

### CODE REVIEW

**Comment by Billy99** [comment]
@soltysh I was just wondering on the status of this PR? I need the openshift/api vendor bumped to the latest to pull in the `DownwardAPIHugePages` FeatureGate changes before Feature Freeze. I started a PR to bring it in and saw this PR already had it. Would it be helpful for me to continue with my PR or is this PR going in soon? Thanks, Billy McFall

**Comment by soltysh** [comment]
I'm waiting for https://github.com/openshift/cluster-kube-apiserver-operator/pull/1035 and the necessary changes to land in api and client-go. But I'm hoping this week to land this too.

**Pull request merged**
