### PR TITLE
WIP: DO NOT MERGE: test looking for lost vsphere request

### PR DESCRIPTION
**Pull request by jupierce**

### CODE REVIEW

**Comment by jupierce** [comment]
/payload periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-upi

**Comment by jupierce** [comment]
/payload periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-upi

**Comment by jupierce** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-upi

**Comment by jupierce** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-upi

**Comment by jupierce** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-upi

**Comment by dgoodwin** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.15-e2e-gcp-ovn-upgrade 10

**Comment by jupierce** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-upgrade-from-stable-4.15-e2e-vsphere-upgrade

**Pull request closed without merging**
