### PR TITLE
Add a defaultNodeSelector

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
DefaultNodeSelector as a back-up for https://github.com/openshift/origin/pull/22554 if we are not able to arrive at conclusion before code freeze.

/cc @sjenning @deads2k

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
I still need to test this out.

**Comment by deads2k** [comment]
/test all

let's see what we've got

**Comment by deads2k** [comment]
/approve

I'll leave lgtm with
/assign @sjenning

**Comment by sjenning** [comment]
/lgtm
thanks Ravi!

**Pull request merged**
