### PR TITLE
WRKLDS-1449: remove resource.k8s.io/v1alpha2 to prepare for upgrade to v1alpha3

### PR DESCRIPTION
**Pull request by atiratree**

### CODE REVIEW

**Comment by atiratree** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-gcp-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-techpreview

**Comment by atiratree** [comment]
closing in favor of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1731 and https://github.com/openshift/installer/pull/8973

**Pull request closed without merging**
