### PR TITLE
Bug 1921139: Revert "remove override for fast cert rotation for release"

### PR DESCRIPTION
**Pull request by sttts**
Inverse of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1143 for master branch during development of 4.9.

### CODE REVIEW

**Comment by sttts** [comment]
/hold cancel

Merge after master has reopened.

**Comment by mfojtik** [comment]
/override ci/prow/e2e-gcp-operator 
/override ci/prow/e2e-upgrade

First has multus problem that is already reported and known.
Second failure seems to be related to SCC (auth team know).

**Pull request merged**
