### PR TITLE
Set short rotation period

### PR DESCRIPTION
**Pull request by soltysh**
/assign @deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
let's try again now that we fixed trust

/lgtm

**Comment by smarterclayton** [comment]
/hold

I want to see this pass e2e-AWS three times before it merges

**Comment by smarterclayton** [comment]
```
    Command stdout:
    
    stderr:
    Error from server: error dialing backend: x509: certificate signed by unknown authority
    
    error:
    exit status 1
```

**Comment by deads2k** [comment]
This is neat.  CSR signer updates enter and kick revisions.  Somehow we're stuck back at revision 10 that is 15 minutes old and revision 14 is available.  Still investigating.

**Comment by deads2k** [comment]
https://github.com/openshift/cluster-kube-controller-manager-operator/pull/261 may fix it have a look

**Comment by deads2k** [comment]
now that https://github.com/openshift/cluster-kube-controller-manager-operator/pull/261 has merged

/test e2e-aws

**Comment by soltysh** [comment]
@deads2k so I bumped this to 4m, which should give us validity of 2h, and 1h rotation time.

**Comment by soltysh** [comment]
This should be possible to merge after https://github.com/openshift/cluster-kube-controller-manager-operator/pull/260

**Comment by deads2k** [comment]
terraform

/retest

1 success
/test e2e-aws

**Comment by soltysh** [comment]
Looks like that e2e operator failure is real, looking into it...

**Comment by deads2k** [comment]
we're still rolling out `"message": "new revision 8 triggered by \"secret/kube-apiserver-cert-syncer-client-cert-key has changed\"",` and it's not graceful.

**Comment by soltysh** [comment]
Now I'm confused, I run this with updated controller and the tests worked fine for me. Rebased and let's see how this plays out now.

**Comment by soltysh** [comment]
Not needed currently.

**Pull request closed without merging**
