### PR TITLE
Bug 1891742: bump(library-go): controller/staticpod: reduce noise of not-ready containers

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by xingxingxia** [comment]
I'm following JIRA issue [DPTP-660](https://issues.redhat.com/browse/DPTP-660) to do the pre-merge verification. The bug is pre-merge verified in [1891742#c5](https://bugzilla.redhat.com/show_bug.cgi?id=1891742#c5). So per JIRA issue [DPTP-660](https://issues.redhat.com/browse/DPTP-660)'s Description process, adding QE lgtm:
/lgtm

**Comment by ashcrow** [comment]
I can't seem to find the PR that when into the main branch. Is this a 4.6 update only?

**Comment by p0lyn0mial** [comment]
> I can't seem to find the PR that when into the main branch. Is this a 4.6 update only?

I think it was introduced in https://github.com/openshift/library-go/pull/930

**Pull request merged**
