### PR TITLE
Bug 1802161: `regenerate-certificates` command blocked by error `illegal base64 data at input byte 3`

### PR DESCRIPTION
**Pull request by p0lyn0mial**

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/hold

for a manual smoke test

**Comment by sttts** [comment]
Clean pick?

**Comment by p0lyn0mial** [comment]
> Clean pick?

almost, had to regenerate bindata. Anyway, I have just successfully performed a manual smoke test - all good.  Ready to be merged.

**Pull request merged**
