### PR TITLE
Bug 1909600: static-pods: retry failed installers

### PR DESCRIPTION
**Pull request by sttts**
Proof of https://github.com/openshift/library-go/pull/979.

Includes https://github.com/openshift/cluster-kube-apiserver-operator/pull/1078.

### CODE REVIEW

**Comment by soltysh** [comment]
I looked through e2e logs searching for the newly added elements, but apparently none was triggered. Have you considered artificially failing one rollout to see if this is working as expected, either programmatically in CI or manually?

**Comment by sttts** [comment]
> I looked through e2e logs searching for the newly added elements, but apparently none was triggered. Have you considered artificially failing one rollout to see if this is working as expected, either programmatically in CI or manually?

I didn't yet. But we should do that, yes.

**Comment by sttts** [comment]
/retest

Flakes?

**Comment by sttts** [comment]
Flakes

/retest

**Pull request merged**
