### PR TITLE
Bug 1961173: bump(*): library-go update

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
passing the encryption tests might be hard

for `e2e-aws-operator-encryption` we need - https://github.com/openshift/cluster-kube-apiserver-operator/pull/1131
for `e2e-aws-operator-encryption-perf ` - I don't know yet, investigating

**Comment by mfojtik** [comment]
@p0lyn0mial we can override those if they are in the works... unless you want to finish them before bump?

**Comment by mfojtik** [comment]
test verify-deps

**Comment by mfojtik** [comment]
/test all

(actually, we want to retest on go 1.16 now)

**Comment by mfojtik** [comment]
/override ci/prow/e2e-aws-operator

this test is not required AND we replaced this with e2e-gcp-operator

**Pull request merged**
