### PR TITLE
Bug 1969633: pkg/operator/targetconfigcontroller: wait for kcm-o to generate certs before rollout

### PR DESCRIPTION
**Pull request by hexfusion**
openshift-managed-config configmap csr-controller-ca is a critical resource for the cluster and is generated by openshift-kube-apiserver-operator render command using ca minted on the installer. When KCM-O starts it deletes and replaces this resource and then manages cert rotation moving forward.

The PR fixes a race condition in SNO where if etcd and or kas rollout and generate disruption before the ca pivots manager we can brick the cluster if the operator loses leadership before the resource is generated. This can lead to node Not Ready and the operator not able to start again. Now we wait for the signal of pivot then continue rollout.

cc @soltysh

related to: https://github.com/openshift/cluster-etcd-operator/pull/619

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by hexfusion** [comment]
hmm same failure in unrelated PR https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-apiserver-operator/1165/pull-ci-openshift-cluster-kube-apiserver-operator-master-k8s-e2e-gcp/1410596889639784448

/test k8s-e2e-gcp

**Comment by hexfusion** [comment]
> KubeDeploymentReplicasMismatch

/test e2e-upgrade

**Comment by hexfusion** [comment]
aws SNO test is known failure: https://coreos.slack.com/archives/CEKNRGF25/p1625042809390700

/skip

**Comment by hexfusion** [comment]
upgrade should pass once https://github.com/openshift/cluster-monitoring-operator/pull/1259 is promoted

**Pull request merged**
