### PR TITLE
make config observation faster

### PR DESCRIPTION
**Pull request by deads2k**
/hold

### CODE REVIEW

**Comment by deads2k** [comment]
@openshift/sig-master who's ready for this? We'd do it library-go

**Comment by deads2k** [comment]
passed except for a known flake.  We could do this.

/hold

hold because it should be library-go first

**Comment by mfojtik** [comment]
/retest

(all known flakes)

**Comment by deads2k** [comment]
we're going for this.  We're going go to get this in a bump

**Pull request closed without merging**
