### PR TITLE
[release-4.14]OCPBUGS-31354: add SNO control plane high cpu usage alert

### PR DESCRIPTION
**Pull request by qJkee**
Manual backport of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1680 and https://github.com/openshift/cluster-kube-apiserver-operator/pull/1676

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
any conflicts when moving ?

**Comment by wangke19** [comment]
The PR has been pre-merge verified and got the expected results. detail see https://issues.redhat.com/browse/OCPBUGS-31354?focusedId=25067523&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25067523****

**Comment by p0lyn0mial** [comment]
> @qJkee was there any conflicts, can you please share the diffs?

@qJkee reached out to me via Slack, saying there was a small conflict in the `starter.go` file.

I have checked and the `starter.go` file matches 4.15 PR - https://github.com/openshift/cluster-kube-apiserver-operator/pull/1706/files#diff-0d623dfd885adb20f991bda4c2453aebd732ca6dbb4d1d4be6e79805c3b48de6

/lgtm


@tkashem please add the `backport-risk-assessed` label - thanks.

**Pull request merged**
