### PR TITLE
Bug 1858763: static-pod-installer: remove deadlock by recreating installers that disappear

### PR DESCRIPTION
**Pull request by sttts**
Pulling in https://github.com/openshift/library-go/pull/871.

### CODE REVIEW

**Comment by hexfusion** [comment]
@sttts is this missing go mod vendor? why no diff on vendor/?

**Comment by sttts** [comment]
/hold

https://github.com/openshift/cluster-kube-apiserver-operator/pull/939#issuecomment-681641238

**Comment by sttts** [comment]
/hold cancel

Thanks @hexfusion for noticing.

**Comment by sttts** [comment]
Scheduler and OLM flakes

/retest

**Comment by sttts** [comment]
Infra sigh.

/retest

**Pull request merged**
